### ISSUE TITLE
feat: implement mastery strategy

### ISSUE THREAD

**Issue by rafaykhan-source** [EthanHaque/hifz#9]
The mastery strategy is a framework to allow users to "eliminate" cards once they've hit a threshold for the number of times they've gotten it correct. Specifically, we may, for example, make it such that any card that has been guessed correctly at least three times will not be shown again.

Below I delineate some obstacles:
1. There is no feedback mechanism yet implemented, and it is unknown whether we want to track feedback in the card, strategy, or via another session based object.
2. Operating by the described paradigm above implies that at some point we run out of cards, and for our basic strategies, we can get new cards infinitely. 
3. The maintenance of something like a frequency map should be independent of the cards, as we have not decided whether to make them hashable.

**Comment by EthanHaque** [comment]
This also begs the question of whether we should have an interface/mechanism for ending a cardsession? It seems strange to have sessions last indefinitely as the default.

**Comment by rafaykhan-source** [comment]
I'm adding some further thoughts with respect to obstacles:
1. We can start by adding a dictionary to store some notion of feedback (which will be easily refactorable once we figure out exactly how we want feedback to look) 
2. To implement the effect of mastery but avoid the issue of running out of cards, we can simply make the next card the card that has been answered correctly the least amount of times, so they are constantly forced to work on their "weakest" card. Some alternative names: WeakestCardStrategy, StrengtheningStrategy.
3. The frequency map can track the index of the card, rather than the card itself.
